# Generated by Django 4.2.2 on 2023-06-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_inventory', models.IntegerField()),
                ('total_products', models.IntegerField()),
                ('average_quantity', models.FloatField()),
                ('low_stock_items', models.IntegerField()),
                ('out_of_stock_items', models.IntegerField()),
                ('average_inventory_value', models.FloatField()),
                ('inventory_turnover', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='location',
            new_name='location_in_store',
        ),
        migrations.CreateModel(
            name='StoreKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_inventory', models.IntegerField()),
                ('total_products', models.IntegerField()),
                ('average_quantity', models.FloatField()),
                ('low_stock_items', models.IntegerField()),
                ('out_of_stock_items', models.IntegerField()),
                ('average_inventory_value', models.FloatField()),
                ('inventory_turnover', models.FloatField()),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LittleLemonAPI.store')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='LittleLemonAPI.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='LittleLemonAPI.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='LittleLemonAPI.store'),
        ),
    ]
