# Generated by Django 4.2.2 on 2023-06-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0005_globalkpi_store_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storekpi',
            options={'verbose_name_plural': 'Store KPIs'},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='available_quantity',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_retrieved',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='LittleLemonAPI.product'),
        ),
    ]
