# Generated by Django 4.2.2 on 2023-06-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0007_tokenproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenProxy',
        ),
    ]
