# Generated by Django 4.2.2 on 2023-06-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0008_delete_tokenproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(default='sousse', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='first-store', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LittleLemonAPI.store'),
            preserve_default=False,
        ),
    ]
