# Generated by Django 4.2.2 on 2023-06-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0009_alter_store_location_alter_store_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LittleLemonAPI.store'),
        ),
    ]
