# Generated by Django 4.2.2 on 2023-06-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0011_alter_user_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='user',
        ),
    ]
