# Generated by Django 4.2.2 on 2023-06-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0013_stocktransaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='location',
        ),
    ]
