# Generated by Django 4.2.2 on 2023-06-30 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('LittleLemonAPI', '0015_alter_user_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_auth_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to='authtoken.token'),
        ),
    ]
