# Generated by Django 4.2.2 on 2023-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0016_user_custom_auth_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storekpi',
            options={},
        ),
        migrations.AlterField(
            model_name='storekpi',
            name='average_inventory_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='storekpi',
            name='average_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='storekpi',
            name='inventory_turnover',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='storekpi',
            name='low_stock_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storekpi',
            name='out_of_stock_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storekpi',
            name='total_inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storekpi',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
    ]
