# Generated by Django 4.2.2 on 2023-07-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0018_salesorderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalkpi',
            name='total_inventory',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='globalkpi',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
    ]
