# Generated by Django 4.2.2 on 2023-07-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0020_alter_globalkpi_average_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalkpi',
            name='average_inventory_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='globalkpi',
            name='inventory_turnover',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='globalkpi',
            name='low_stock_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='globalkpi',
            name='out_of_stock_items',
            field=models.IntegerField(default=0),
        ),
    ]
