# Generated by Django 4.2.2 on 2023-07-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0022_remove_storekpi_inventory_turnover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storekpi',
            name='average_inventory_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
